swagger: "2.0"
info:
  title: AWS Certificate Manager API
  version: 1.0.0
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths:
  /?Action=AddTagsToCertificate&k=1:
    get:
      summary: Adds one or more tags to an ACM Certificate.
      description: Adds one or more tags to an ACM Certificate.
      operationId: AddTagsToCertificate
      parameters:
      - in: query
        name: CertificateArn
        description: 'String that contains the ARN of the ACM Certificate to which
          the tag is to be applied.      This must be of the form:'
        type: string
      - in: query
        name: Tags
        description: The key-value pair that defines the tag. The tag value is optional.
        type: string
      responses:
        200:
          description: OK
      tags:
      - Certificate Tags
  /?Action=DeleteCertificate&k=1:
    get:
      summary: Deletes an ACM Certificate and its associated private key.
      description: Deletes an ACM Certificate and its associated private key.
      operationId: DeleteCertificate
      parameters:
      - in: query
        name: CertificateArn
        description: 'String that contains the ARN of the ACM Certificate to be deleted.
          This must be of the      form:'
        type: string
      responses:
        200:
          description: OK
      tags:
      - Certificates
  /?Action=DescribeCertificate&k=1:
    get:
      summary: Returns a list of the fields contained in the specified ACM Certificate.
      description: Returns a list of the fields contained in the specified ACM Certificate.
      operationId: DescribeCertificate
      parameters:
      - in: query
        name: CertificateArn
        description: 'String that contains an ACM Certificate ARN. The ARN must be
          of the form:'
        type: string
      responses:
        200:
          description: OK
      tags:
      - Certificates
  /?Action=GetCertificate&k=1:
    get:
      summary: Retrieves an ACM Certificate and certificate chain for the certificate
        specified by ann      ARN.
      description: Retrieves an ACM Certificate and certificate chain for the certificate
        specified by an      ARN.
      operationId: GetCertificate
      parameters:
      - in: query
        name: CertificateArn
        description: 'String that contains a certificate ARN in the following format:'
        type: string
      responses:
        200:
          description: OK
      tags:
      - Certificates
  /?Action=ImportCertificate&k=1:
    get:
      summary: Imports an SSL/TLS certificate into AWS Certificate Manager (ACM) to
        use with.
      description: Imports an SSL/TLS certificate into AWS Certificate Manager (ACM)
        to use with.
      operationId: ImportCertificate
      parameters:
      - in: query
        name: Certificate
        description: 'The certificate to import. It must meet the following requirements:'
        type: string
      - in: query
        name: CertificateArn
        description: The Amazon Resource Name        (ARN) of an imported certificate
          to replace. To import a new certificate, omit this      field.
        type: string
      - in: query
        name: CertificateChain
        description: The certificate chain. It must be PEM-encoded.
        type: string
      - in: query
        name: PrivateKey
        description: 'The private key that matches the public key in the certificate.
          It must meet the      following requirements:'
        type: string
      responses:
        200:
          description: OK
      tags:
      - Certificates
  /?Action=ListCertificates&k=1:
    get:
      summary: Retrieves a list of ACM Certificates and the domain name for each.
      description: Retrieves a list of ACM Certificates and the domain name for each.
      operationId: ListCertificates
      parameters:
      - in: query
        name: CertificateStatuses
        description: The status or statuses on which to filter the list of ACM Certificates.
        type: string
      - in: query
        name: MaxItems
        description: Use this parameter when paginating results to specify the maximum
          number of items to      return in the response. If additional items exist
          beyond the number you specify, the        NextToken element is sent in the
          response. Use this NextToken value      in a subsequent request to retrieve
          additional items.
        type: string
      - in: query
        name: NextToken
        description: Use this parameter only when paginating results and only in a
          subsequent request after      you receive a response with truncated results.
          Set it to the value of NextToken      from the response you just received.
        type: string
      responses:
        200:
          description: OK
      tags:
      - Certificates
  /?Action=ListTagsForCertificate&k=1:
    get:
      summary: Lists the tags that have been applied to the ACM Certificate.
      description: Lists the tags that have been applied to the ACM Certificate.
      operationId: ListTagsForCertificate
      parameters:
      - in: query
        name: CertificateArn
        description: 'String that contains the ARN of the ACM Certificate for which
          you want to list the      tags. This must be of the form:'
        type: string
      responses:
        200:
          description: OK
      tags:
      - Certificate Tags
  /?Action=RemoveTagsFromCertificate&k=1:
    get:
      summary: Remove one or more tags from an ACM Certificate.
      description: Remove one or more tags from an ACM Certificate.
      operationId: RemoveTagsFromCertificate
      parameters:
      - in: query
        name: CertificateArn
        description: 'String that contains the ARN of the ACM Certificate with one
          or more tags that you want      to remove. This must be of the form:'
        type: string
      - in: query
        name: Tags
        description: The key-value pair that defines the tag to remove.
        type: string
      responses:
        200:
          description: OK
      tags:
      - Certificate Tags
  /?Action=RequestCertificate&k=1:
    get:
      summary: Requests an ACM Certificate for use with other AWS services.
      description: Requests an ACM Certificate for use with other AWS services.
      operationId: RequestCertificate
      parameters:
      - in: query
        name: DomainName
        description: Fully qualified domain name (FQDN), such as www.example.com,
          of the site you want to      secure with an ACM Certificate. Use an asterisk
          (*) to create a wildcard certificate that      protects several sites in
          the same domain. For example, *.example.com protects      www.example.com,
          site.example.com, and images.example.com.
        type: string
      - in: query
        name: DomainValidationOptions
        description: 'The base validation domain that will act as the suffix of the
          email addresses that are      used to send the emails. This must be the
          same as the Domain value or a      superdomain of the Domain value. For
          example, if you requested a certificate for        test.example.com and
          specify DomainValidationOptions of example.com, ACM sends email to the      domain
          registrant, technical contact, and administrative contact in WHOIS and the
          following      five addresses:'
        type: string
      - in: query
        name: IdempotencyToken
        description: Customer chosen string that can be used to distinguish between
          calls to        RequestCertificate. Idempotency tokens time out after one
          hour. Therefore, if      you call RequestCertificate multiple times with
          the same idempotency token within      one hour, ACM recognizes that you
          are requesting only one certificate and will issue only one.      If you
          change the idempotency token for each call, ACM recognizes that you are
          requesting      multiple certificates.
        type: string
      - in: query
        name: SubjectAlternativeNames
        description: Additional FQDNs to be included in the Subject Alternative Name
          extension of the ACM      Certificate. For example, add the name www.example.net
          to a certificate for which the        DomainName field is www.example.com
          if users can reach your site by using      either name.
        type: string
      responses:
        200:
          description: OK
      tags:
      - Certificates
  /?Action=ResendValidationEmail&k=1:
    get:
      summary: Resends the email that requests domain ownership validation.
      description: Resends the email that requests domain ownership validation.
      operationId: ResendValidationEmail
      parameters:
      - in: query
        name: CertificateArn
        description: String that contains the ARN of the requested certificate. The
          certificate ARN is      generated and returned by the RequestCertificate
          action as soon as the      request is made. By default, using this parameter
          causes email to be sent to all top-level      domains you specified in the
          certificate request.
        type: string
      - in: query
        name: Domain
        description: The Fully Qualified Domain Name (FQDN) of the certificate that
          needs to be      validated.
        type: string
      - in: query
        name: ValidationDomain
        description: 'The base validation domain that will act as the suffix of the
          email addresses that are      used to send the emails. This must be the
          same as the Domain value or a      superdomain of the Domain value. For
          example, if you requested a certificate for        site.subdomain.example.com
          and specify a ValidationDomain of subdomain.example.com, ACM sends email
          to the      domain registrant, technical contact, and administrative contact
          in WHOIS and the following      five addresses:'
        type: string
      responses:
        200:
          description: OK
      tags:
      - Validation Email
definitions: []