swagger: "2.0"
info:
  title: AWS Polly API
  version: 1.0.0
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths:
  /?Action=DeleteLexicon&k=1:
    get:
      summary: ' Delete Lexicon '
      description: Deletes the specified pronunciation lexicon stored in an AWS Region.
      operationId: deleteLexicon
      parameters:
      - in: query
        name: Name
        description: The name of the lexicon to delete.       Must be an existing
          lexicon in the region.
        type: string
      responses:
        200:
          description: OK
      tags:
      - Lexicons
  /?Action=DescribeVoices&k=1:
    get:
      summary: ' Describe Voices '
      description: Returns the list of voices that are available for use when requesting
        speech synthesis.
      operationId: describeVoices
      parameters:
      - in: query
        name: LanguageCode
        description: The language identification tag (ISO 639 code for the language
          name-ISO 3166 country code)       for filtering the list of voices returned.     If
          you dont specify this optional parameter, all available voices are returned.
        type: string
      - in: query
        name: NextToken
        description: An opaque pagination token returned from the previous     DescribeVoices
          operation. If present, this indicates where to     continue the listing.
        type: string
      responses:
        200:
          description: OK
      tags:
      - voices
  /?Action=GetLexicon&k=1:
    get:
      summary: ' Get Lexicon '
      description: Returns the content of the specified pronunciation lexicon stored
        in an AWS Region.
      operationId: getLexicon
      parameters:
      - in: query
        name: Name
        description: Name of the lexicon.
        type: string
      responses:
        200:
          description: OK
      tags:
      - Lexicons
  /?Action=ListLexicons&k=1:
    get:
      summary: ' List Lexicons '
      description: Returns a list of pronunciation lexicons stored in an AWS Region.
      operationId: listLexicons
      parameters:
      - in: query
        name: NextToken
        description: An opaque pagination token returned from previous       ListLexicons
          operation. If present, indicates where to       continue the list of lexicons.
        type: string
      responses:
        200:
          description: OK
      tags:
      - Lexicons
  /?Action=PutLexicon&k=1:
    get:
      summary: ' Put Lexicon '
      description: Stores a pronunciation lexicon in an AWS Region.
      operationId: putLexicon
      parameters:
      - in: query
        name: Name
        description: Name of the lexicon. The name must follow the regular express
          format       [0-9A-Za-z]{1,20}.      That is, the name is a case-sensitive
          alphanumeric string up to 20 characters long.
        type: string
      responses:
        200:
          description: OK
      tags:
      - Lexicons
  /?Action=SynthesizeSpeech&k=1:
    get:
      summary: ' Synthesize Speech '
      description: Synthesizes UTF-8 input, plain text or SSML, to a stream of bytes.
      operationId: synthesizeSpeech
      parameters:
      - in: query
        name: LexiconNames
        description: List of one or more pronunciation lexicon names you want the
          service to apply      during synthesis. Lexicons are applied only if the
          language of the lexicon is the same      as the language of the voice. For
          information about storing lexicons,       see PutLexicon.
        type: string
      - in: query
        name: OutputFormat
        description: The audio format in which the resulting stream will be encoded.
        type: string
      - in: query
        name: SampleRate
        description: The audio frequency specified in Hz.
        type: string
      - in: query
        name: Text
        description: Input text to synthesize. If you specify       ssml as the TextType,
          follow the SSML format for the       input text.
        type: string
      - in: query
        name: TextType
        description: Specifies whether the input text is plain text or SSML. The default
          value is plain text.      For more information, see Using SSML.
        type: string
      - in: query
        name: VoiceId
        description: Voice ID to use for the synthesis. You can get a list of       available
          voice IDs by calling the DescribeVoices operation.
        type: string
      responses:
        200:
          description: OK
      tags:
      - Speech
definitions: []