swagger: "2.0"
info:
  title: AWS Kinesis Analytics API
  version: 1.0.0
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths:
  /?Action=AddApplicationInput&k=1:
    get:
      summary: ' Add Application Input '
      description: Adds a streaming source to your Amazon Kinesis application.
      operationId: addApplicationInput
      parameters:
      - in: query
        name: ApplicationName
        description: Name of your existing Amazon Kinesis Analytics application to
          which you want to add the streaming source.
        type: string
      - in: query
        name: CurrentApplicationVersionId
        description: Current version of your Amazon Kinesis Analytics application.
          You can use the DescribeApplication operation             to find the current
          application version.
        type: string
      - in: query
        name: Input
        description: When you configure the application input, you specify the streaming
          source,  the         in-application stream name that is created, and the
          mapping between the two.         For more information,         see Configuring
          Application Input.
        type: string
      responses:
        200:
          description: OK
      tags:
      - Applications
  /?Action=AddApplicationOutput&k=1:
    get:
      summary: ' Add Application Output '
      description: Adds an external destination to your Amazon Kinesis Analytics application.
      operationId: addApplicationOutput
      parameters:
      - in: query
        name: ApplicationName
        description: Name of the application to which you want to add the output configuration.
        type: string
      - in: query
        name: CurrentApplicationVersionId
        description: Version of the application to which you want add the             output
          configuration. You can use the DescribeApplication operation             to
          get the current application version.        If the version specified is
          not the current version, the             ConcurrentModificationException
          is returned.
        type: string
      - in: query
        name: Output
        description: An array of objects, each describing one output configuration.
          In the output configuration, you specify the name of an in-application stream,
          a destination (that is, an Amazon Kinesis stream or an Amazon Kinesis Firehose
          delivery stream), and record the formation to use when writing to the destination.
        type: string
      responses:
        200:
          description: OK
      tags:
      - Applications
  /?Action=AddApplicationReferenceDataSource&k=1:
    get:
      summary: ' Add Application Reference Data Source '
      description: Adds a reference data source to an existing application.
      operationId: addApplicationReferenceDataSource
      parameters:
      - in: query
        name: ApplicationName
        description: Name of an existing application.
        type: string
      - in: query
        name: CurrentApplicationVersionId
        description: Version of the application for which you are adding the reference
          data source.             You can use the DescribeApplication operation to
          get the current application version.            If the version specified
          is not the current version, the             ConcurrentModificationException
          is returned.
        type: string
      - in: query
        name: ReferenceDataSource
        description: The reference data source can be an object in your Amazon S3
          bucket. Amazon Kinesis Analytics reads the object and copies the data into
          the in-application table that is created. You provide an S3 bucket, object
          key name, and the resulting in-application table that is created. You must
          also provide an IAM role with the necessary permissions that Amazon Kinesis
          Analytics can assume to read the object from your S3 bucket on your behalf.
        type: string
      responses:
        200:
          description: OK
      tags:
      - Applications
  /?Action=CreateApplication&k=1:
    get:
      summary: ' Create Application '
      description: Creates an Amazon Kinesis Analytics application.
      operationId: createApplication
      parameters:
      - in: query
        name: ApplicationCode
        description: One or more SQL statements that read input data, transform it,             and
          generate output. For example, you can write a SQL statement             that
          reads data from one in-application stream,              generates a running
          average of the number             of advertisement clicks by vendor, and
          insert resulting rows in             another in-application stream using
          pumps.         For more inforamtion about the typical pattern, see             Application
          Code.
        type: string
      - in: query
        name: ApplicationDescription
        description: Summary description of the application.
        type: string
      - in: query
        name: ApplicationName
        description: Name of your Amazon Kinesis Analytics application (for example,
          sample-app).
        type: string
      - in: query
        name: Inputs
        description: Use this parameter to configure the application input.
        type: string
      - in: query
        name: Outputs
        description: You can configure application output to write data from any of
          the in-application streams to up to five destinations.
        type: string
      responses:
        200:
          description: OK
      tags:
      - Applications
  /?Action=DeleteApplication&k=1:
    get:
      summary: ' Delete Application '
      description: Deletes the specified application.
      operationId: deleteApplication
      parameters:
      - in: query
        name: ApplicationName
        description: Name of the Amazon Kinesis Analytics application to delete.
        type: string
      - in: query
        name: CreateTimestamp
        description: You can use the DescribeApplication operation to get this value.
        type: string
      responses:
        200:
          description: OK
      tags:
      - Applications
  /?Action=DeleteApplicationOutput&k=1:
    get:
      summary: ' Delete Application Output '
      description: Deletes output destination configuration from your application
        configuration.
      operationId: deleteApplicationOutput
      parameters:
      - in: query
        name: ApplicationName
        description: Amazon Kinesis Analytics application name.
        type: string
      - in: query
        name: CurrentApplicationVersionId
        description: Amazon Kinesis Analytics application version.             You
          can use the DescribeApplication operation to get the current application
          version.            If the version specified is not the current version,
          the             ConcurrentModificationException is returned.
        type: string
      - in: query
        name: OutputId
        description: The ID of the configuration to delete.             Each output
          configuration that is added to the application, either when the application
          is             created or later using the AddApplicationOutput operation,
          has a unique ID.             You need to provide the ID to uniquely identify
          the output configuration that you want to             delete from the application
          configuration.             You can use the DescribeApplication operation
          to get the specific             OutputId.
        type: string
      responses:
        200:
          description: OK
      tags:
      - Applications
  /?Action=DeleteApplicationReferenceDataSource&k=1:
    get:
      summary: ' Delete Application Reference Data Source '
      description: Deletes a reference data source configuration from the specified
        application configuration.
      operationId: deleteApplicationReferenceDataSource
      parameters:
      - in: query
        name: ApplicationName
        description: Name of an existing application.
        type: string
      - in: query
        name: CurrentApplicationVersionId
        description: Version of the application.              You can use the DescribeApplication
          operation to get the current application version.            If the version
          specified             is not the current version, the ConcurrentModificationException
          is returned.
        type: string
      - in: query
        name: ReferenceId
        description: ID of the reference data source. When you add a reference data
          source to your             application using the             AddApplicationReferenceDataSource,
          Amazon Kinesis Analytics assigns an ID.             You can use the DescribeApplication
          operation to get the reference ID.
        type: string
      responses:
        200:
          description: OK
      tags:
      - Applications
  /?Action=DescribeApplication&k=1:
    get:
      summary: ' Describe Application '
      description: Returns information about a specific Amazon Kinesis Analytics application.
      operationId: describeApplication
      parameters:
      - in: query
        name: ApplicationName
        description: Name of the application.
        type: string
      responses:
        200:
          description: OK
      tags:
      - Applications
  /?Action=DiscoverInputSchema&k=1:
    get:
      summary: ' Discover Input Schema '
      description: Infers a schema by evaluating sample records on the specified streaming
        source (Amazon Kinesis stream or Amazon Kinesis Firehose delivery stream).
      operationId: discoverInputSchema
      parameters:
      - in: query
        name: InputStartingPositionConfiguration
        description: Point at which you want Amazon Kinesis Analytics to start reading
          records from the specified streaming source discovery purposes.
        type: string
      - in: query
        name: ResourceARN
        description: Amazon Resource Name (ARN) of the streaming source.
        type: string
      - in: query
        name: RoleARN
        description: ARN of the IAM role that Amazon Kinesis Analytics can assume
          to access the stream on your behalf.
        type: string
      responses:
        200:
          description: OK
      tags:
      - Schema
  /?Action=ListApplications&k=1:
    get:
      summary: ' List Applications '
      description: 'Returns a list of Amazon Kinesis Analytics applications in your
        account. '
      operationId: listApplications
      responses:
        200:
          description: OK
      tags:
      - Applications
  /?Action=StartApplication&k=1:
    get:
      summary: ' Start Application '
      description: Starts the specified Amazon Kinesis Analytics application.
      operationId: startApplication
      parameters:
      - in: query
        name: ApplicationName
        description: Name of the application.
        type: string
      - in: query
        name: InputConfigurations
        description: Identifies the specific input, by ID, that the application starts
          consuming. Amazon Kinesis Analytics starts reading the streaming source
          associated with the input. You can also specify where in the streaming source
          you want Amazon Kinesis Analytics to start reading.
        type: string
      responses:
        200:
          description: OK
      tags:
      - Applications
  /?Action=StopApplication&k=1:
    get:
      summary: ' Stop Application '
      description: Stops the application from processing input data.
      operationId: stopApplication
      parameters:
      - in: query
        name: ApplicationName
        description: Name of the running application to stop.
        type: string
      responses:
        200:
          description: OK
      tags:
      - Applications
  /?Action=UpdateApplication&k=1:
    get:
      summary: ' Update Application '
      description: Updates an existing Amazon Kinesis Analytics application.
      operationId: updateApplication
      parameters:
      - in: query
        name: ApplicationName
        description: Name of the Amazon Kinesis Analytics application to update.
        type: string
      - in: query
        name: ApplicationUpdate
        description: Describes application updates.
        type: string
      - in: query
        name: CurrentApplicationVersionId
        description: The current application version ID. You can use the             DescribeApplication
          operation to get this value.
        type: string
      responses:
        200:
          description: OK
      tags:
      - Applications
definitions: []