swagger: "2.0"
info:
  title: Amazon CloudWatch API
  version: 1.0.0
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths:
  /?Action=DeleteAlarms&k=1:
    "":
      summary: Delete Alarms
      description: Deletes the specified alarms.
      operationId: deletealarms
      parameters:
      - in: query
        name: AlarmNames.member.N
        description: The alarms to be deleted.
        type: string
      responses:
        200:
          description: OK
      tags:
      - Alarms
  /?Action=DescribeAlarmHistory&k=1:
    "":
      summary: Describe Alarm History
      description: Retrieves the history for the specified alarm.
      operationId: describealarmhistory
      parameters:
      - in: query
        name: AlarmName
        description: The name of the alarm.
        type: string
      - in: query
        name: EndDate
        description: The ending date to retrieve alarm history.
        type: string
      - in: query
        name: HistoryItemType
        description: The type of alarm histories to retrieve.
        type: string
      - in: query
        name: MaxRecords
        description: The maximum number of alarm history records to retrieve.
        type: string
      - in: query
        name: NextToken
        description: The token returned by a previous call to indicate that there
          is more datatttavailable.
        type: string
      - in: query
        name: StartDate
        description: The starting date to retrieve alarm history.
        type: string
      responses:
        200:
          description: OK
      tags:
      - Alarm History
  /?Action=DescribeAlarms&k=1:
    "":
      summary: Describe Alarms
      description: Retrieves the specified alarms.
      operationId: describealarms
      parameters:
      - in: query
        name: ActionPrefix
        description: The action name prefix.
        type: string
      - in: query
        name: AlarmNamePrefix
        description: The alarm name prefix. You cannot specify AlarmNames if this
          parametertttis specified.
        type: string
      - in: query
        name: AlarmNames.member.N
        description: The names of the alarms.
        type: string
      - in: query
        name: MaxRecords
        description: The maximum number of alarm descriptions to retrieve.
        type: string
      - in: query
        name: NextToken
        description: The token returned by a previous call to indicate that there
          is more datatttavailable.
        type: string
      - in: query
        name: StateValue
        description: The state value to be used in matching alarms.
        type: string
      responses:
        200:
          description: OK
      tags:
      - Alarms
  /?Action=DescribeAlarmsForMetric&k=1:
    "":
      summary: Describe Alarms For Metric
      description: Retrieves the alarms for the specified metric.
      operationId: describealarmsformetric
      parameters:
      - in: query
        name: Dimensions.member.N
        description: The dimensions associated with the metric. If the metric has
          any associatedtttdimensions, you must specify them in order for the call
          to succeed.
        type: string
      - in: query
        name: ExtendedStatistic
        description: The percentile statistic for the metric. Specify a value betweentt    p0.0
          and p100.
        type: string
      - in: query
        name: MetricName
        description: The name of the metric.
        type: string
      - in: query
        name: Namespace
        description: The namespace of the metric.
        type: string
      - in: query
        name: Period
        description: The period, in seconds, over which the statistic is applied.
        type: string
      - in: query
        name: Statistic
        description: The statistic for the metric, other than percentiles.tt    For
          percentile statistics, use ExtendedStatistics.
        type: string
      - in: query
        name: Unit
        description: The unit for the metric.
        type: string
      responses:
        200:
          description: OK
      tags:
      - Alarm Metrics
  /?Action=DisableAlarmActions&k=1:
    "":
      summary: Disable Alarm Actions
      description: Disables the actions for the specified alarms.
      operationId: disablealarmactions
      parameters:
      - in: query
        name: AlarmNames.member.N
        description: The names of the alarms.
        type: string
      responses:
        200:
          description: OK
      tags:
      - Alarm Actions
  /?Action=EnableAlarmActions&k=1:
    "":
      summary: Enable Alarm Actions
      description: Enables the actions for the specified alarms.
      operationId: enablealarmactions
      parameters:
      - in: query
        name: AlarmNames.member.N
        description: The names of the alarms.
        type: string
      responses:
        200:
          description: OK
      tags:
      - Alarm Actions
  /?Action=GetMetricStatistics&k=1:
    "":
      summary: Get Metric Statistics
      description: Gets statistics for the specified metric.
      operationId: getmetricstatistics
      parameters:
      - in: query
        name: Dimensions.member.N
        description: The dimensions. CloudWatch treats each unique combination of
          dimensions as a separate metric.tt    You cant retrieve statistics using
          combinations of dimensions that were not specially published.tt    You must
          specify the same dimensions that were used when the metrics were created.
          For an example,tt    see Dimension Combinations in the Amazon CloudWatch
          User Guide.
        type: string
      - in: query
        name: EndTime
        description: The time stamp that determines the last data point to return.
        type: string
      - in: query
        name: ExtendedStatistics.member.N
        description: The percentile statistics. Specify values between p0.0 and p100.
        type: string
      - in: query
        name: MetricName
        description: The name of the metric, with or without spaces.
        type: string
      - in: query
        name: Namespace
        description: The namespace of the metric, with or without spaces.
        type: string
      - in: query
        name: Period
        description: The granularity, in seconds, of the returned data points. A period
          cantttbe as short as one minute (60 seconds) and must be a multiple of 60.
          tttThe default value is 60.
        type: string
      - in: query
        name: StartTime
        description: The time stamp that determines the first data point to return.
          Note thattt    start times are evaluated relative to the time that CloudWatch
          receives the request.
        type: string
      - in: query
        name: Statistics.member.N
        description: The metric statistics, other than percentile. For percentile
          statistics,tt    use ExtendedStatistic.
        type: string
      - in: query
        name: Unit
        description: The unit for a given metric. Metrics may be reported in multiple
          units.tttNot supplying a unit results in all units being returned. If the
          metric only evertttreports one unit, specifying a unit has no effect.
        type: string
      responses:
        200:
          description: OK
      tags:
      - Metric Statistics
  /?Action=ListMetrics&k=1:
    "":
      summary: List Metrics
      description: List the specified metrics.
      operationId: listmetrics
      parameters:
      - in: query
        name: Dimensions.member.N
        description: The dimensions to filter against.
        type: string
      - in: query
        name: MetricName
        description: The name of the metric to filter against.
        type: string
      - in: query
        name: Namespace
        description: The namespace to filter against.
        type: string
      - in: query
        name: NextToken
        description: The token returned by a previous call to indicate that there
          is more datatttavailable.
        type: string
      responses:
        200:
          description: OK
      tags:
      - Metrics
  /?Action=PutMetricAlarm&k=1:
    "":
      summary: Put Metric Alarm
      description: Creates or updates an alarm and associates it with the specified
        metric.
      operationId: putmetricalarm
      parameters:
      - in: query
        name: ActionsEnabled
        description: Indicates whether actions should be executed during any changes
          to the alarm state.
        type: string
      - in: query
        name: AlarmActions.member.N
        description: The actions to execute when this alarm transitions to the ALARM
          state from any other state. tttEach action is specified as an Amazon Resource
          Name (ARN).
        type: string
      - in: query
        name: AlarmDescription
        description: The description for the alarm.
        type: string
      - in: query
        name: AlarmName
        description: The name for the alarm. This name must be unique within the AWS
          account.
        type: string
      - in: query
        name: ComparisonOperator
        description: The arithmetic operation to use when comparing the specified
          statistic andtttthreshold. The specified statistic value is used as the
          first operand.
        type: string
      - in: query
        name: Dimensions.member.N
        description: The dimensions for the metric associated with the alarm.
        type: string
      - in: query
        name: EvaluationPeriods
        description: The number of periods over which data is compared to the specifiedtttthreshold.
        type: string
      - in: query
        name: ExtendedStatistic
        description: The percentile statistic for the metric associated with the alarm.
          Specify a value tttbetween p0.0 and p100.
        type: string
      - in: query
        name: InsufficientDataActions.member.N
        description: The actions to execute when this alarm transitions to the INSUFFICIENT_DATA
          state from any other state. tttEach action is specified as an Amazon Resource
          Name (ARN).
        type: string
      - in: query
        name: MetricName
        description: The name for the metric associated with the alarm.
        type: string
      - in: query
        name: Namespace
        description: The namespace for the metric associated with the alarm.
        type: string
      - in: query
        name: OKActions.member.N
        description: The actions to execute when this alarm transitions to an OK statetttfrom
          any other state. Each action is specified as an Amazon Resource Name (ARN).
        type: string
      - in: query
        name: Period
        description: The period, in seconds, over which the specified statistic is
          applied.
        type: string
      - in: query
        name: Statistic
        description: The statistic for the metric associated with the alarm, other
          than percentile.tt    For percentile statistics, use ExtendedStatistic.
        type: string
      - in: query
        name: Threshold
        description: The value against which the specified statistic is compared.
        type: string
      - in: query
        name: Unit
        description: The unit of measure for the statistic. For example, the units
          for the Amazon EC2tttNetworkIn metric are Bytes because NetworkIn tracks
          the number of bytes that an instancetttreceives on all network interfaces.
          You can also specify a unit when you create a customtttmetric. Units help
          provide conceptual meaning to your data. Metric data points thattttspecify
          a unit of measure, such as Percent, are aggregated separately.
        type: string
      responses:
        200:
          description: OK
      tags:
      - Alarm Metric
  /?Action=PutMetricData&k=1:
    "":
      summary: Put Metric Data
      description: Publishes metric data points to Amazon CloudWatch.
      operationId: putmetricdata
      parameters:
      - in: query
        name: MetricData.member.N
        description: The data for the metric.
        type: string
      - in: query
        name: Namespace
        description: The namespace for the metric data.
        type: string
      responses:
        200:
          description: OK
      tags:
      - Data Metric
  /?Action=SetAlarmState&k=1:
    "":
      summary: Set Alarm State
      description: Temporarily sets the state of an alarm for testing purposes.
      operationId: setalarmstate
      parameters:
      - in: query
        name: AlarmName
        description: The name for the alarm. This name must be unique within the AWStttaccount.
          The maximum length is 255 characters.
        type: string
      - in: query
        name: StateReason
        description: The reason that this alarm is set to this specific state, in
          text format.
        type: string
      - in: query
        name: StateReasonData
        description: The reason that this alarm is set to this specific state, in
          JSON format.
        type: string
      - in: query
        name: StateValue
        description: The value of the state.
        type: string
      responses:
        200:
          description: OK
      tags:
      - Aler State
definitions: []