swagger: "2.0"
info:
  title: AWS CloudTrail API
  version: 1.0.0
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths:
  /?Action=AddTags&k=1:
    get:
      summary: Adds one or more tags to a trail, up to a limit of 50.
      description: Adds one or more tags to a trail, up to a limit of 50.
      operationId: AddTags
      parameters:
      - in: query
        name: ResourceId
        description: 'Specifies the ARN of the trail to which one or more tags will
          be added. The format of a trail ARN is:'
        type: string
      - in: query
        name: TagsList
        description: Contains a list of CloudTrail tags, up to a limit of 50
        type: string
      responses:
        200:
          description: OK
      tags:
      - Tags
  /?Action=CreateTrail&k=1:
    get:
      summary: Creates a trail that specifies the settings for delivery of log data
        to an Amazon S3 bucket.
      description: Creates a trail that specifies the settings for delivery of log
        data to an Amazon S3 bucket.
      operationId: CreateTrail
      parameters:
      - in: query
        name: CloudWatchLogsLogGroupArn
        description: Specifies a log group name using an Amazon Resource Name (ARN),
          a unique identifier that represents the log group to which CloudTrail logs
          will be delivered. Not required unless you specify CloudWatchLogsRoleArn.
        type: string
      - in: query
        name: CloudWatchLogsRoleArn
        description: Specifies the role for the CloudWatch Logs endpoint to assume
          to write to a users log group.
        type: string
      - in: query
        name: EnableLogFileValidation
        description: Specifies whether log file integrity validation is enabled. The
          default is false.
        type: string
      - in: query
        name: IncludeGlobalServiceEvents
        description: Specifies whether the trail is publishing events from global
          services such as IAM to the log files.
        type: string
      - in: query
        name: IsMultiRegionTrail
        description: Specifies whether the trail is created in the current region
          or in all regions. The default is false.
        type: string
      - in: query
        name: KmsKeyId
        description: Specifies the KMS key ID to use to encrypt the logs delivered
          by CloudTrail. The value can be a an alias name prefixed by alias/, a fully
          specified ARN to an alias, a fully specified ARN to a key, or a globally
          unique identifier.
        type: string
      - in: query
        name: Name
        description: 'Specifies the name of the trail. The name must meet the following
          requirements:'
        type: string
      - in: query
        name: S3BucketName
        description: Specifies the name of the Amazon S3 bucket designated for publishing
          log files. See Amazon S3 Bucket Naming Requirements.
        type: string
      - in: query
        name: S3KeyPrefix
        description: Specifies the Amazon S3 key prefix that comes after the name
          of the bucket you have designated         for log file delivery. For more
          information, see Finding Your CloudTrail Log Files. The maximum length is
          200 characters.
        type: string
      - in: query
        name: SnsTopicName
        description: Specifies the name of the Amazon SNS topic defined for notification
          of log file delivery. The maximum length is 256 characters.
        type: string
      responses:
        200:
          description: OK
      tags:
      - Trails
  /?Action=DeleteTrail&k=1:
    get:
      summary: Deletes a trail.
      description: Deletes a trail.
      operationId: DeleteTrail
      parameters:
      - in: query
        name: Name
        description: 'Specifies the name or the CloudTrail ARN of the trail to be
          deleted. The format of a trail ARN is:         arn:aws:cloudtrail:us-east-1:123456789012:trail/MyTrail'
        type: string
      responses:
        200:
          description: OK
      tags:
      - Trails
  /?Action=DescribeTrails&k=1:
    get:
      summary: Retrieves settings for the trail associated with the current region
        for your account.
      description: Retrieves settings for the trail associated with the current region
        for your account.
      operationId: DescribeTrails
      parameters:
      - in: query
        name: includeShadowTrails
        description: Specifies whether to include shadow trails in the response. A
          shadow trail is the replication in a region of a trail that was created
          in a different region. The default is true.
        type: string
      - in: query
        name: trailNameList
        description: 'Specifies a list of trail names, trail ARNs, or both, of the
          trails to describe. The format of a trail ARN is:'
        type: string
      responses:
        200:
          description: OK
      tags:
      - Trails
  /?Action=GetEventSelectors&k=1:
    get:
      summary: Describes the settings for the event selectors that you configured
        for your trail.
      description: Describes the settings for the event selectors that you configured
        for your trail.
      operationId: GetEventSelectors
      parameters:
      - in: query
        name: TrailName
        description: 'Specifies the name of the trail or trail ARN. If you specify
          a trail name, the         string must meet the following requirements:'
        type: string
      responses:
        200:
          description: OK
      tags:
      - Event Selectors
  /?Action=GetTrailStatus&k=1:
    get:
      summary: Returns a JSON-formatted list of information about the specified trail.
      description: Returns a JSON-formatted list of information about the specified
        trail.
      operationId: GetTrailStatus
      parameters:
      - in: query
        name: Name
        description: 'Specifies the name or the CloudTrail ARN of the trail for which
          you are requesting status. To get the status of a shadow trail (a replication
          of the trail in another region), you must specify its ARN. The format of
          a trail ARN is:'
        type: string
      responses:
        200:
          description: OK
      tags:
      - Trails
  /?Action=ListPublicKeys&k=1:
    get:
      summary: Returns all public keys whose private keys were used to sign the digest
        files within the specified time range.
      description: Returns all public keys whose private keys were used to sign the
        digest files within the specified time range.
      operationId: ListPublicKeys
      parameters:
      - in: query
        name: EndTime
        description: Optionally specifies, in UTC, the end of the time range to look
          up public keys for CloudTrail digest files. If not specified, the current
          time is used.
        type: string
      - in: query
        name: NextToken
        description: Reserved for future use.
        type: string
      - in: query
        name: StartTime
        description: Optionally specifies, in UTC, the start of the time range to
          look up public keys for CloudTrail digest files. If not specified, the current
          time is used, and the current public key is returned.
        type: string
      responses:
        200:
          description: OK
      tags:
      - Public Keys
  /?Action=ListTags&k=1:
    get:
      summary: Lists the tags for the trail in the current region.
      description: Lists the tags for the trail in the current region.
      operationId: ListTags
      parameters:
      - in: query
        name: NextToken
        description: Reserved for future use.
        type: string
      - in: query
        name: ResourceIdList
        description: 'Specifies a list of trail ARNs whose tags will be listed. The
          list has a limit of 20 ARNs. The format of a trail ARN is:'
        type: string
      responses:
        200:
          description: OK
      tags:
      - Service Access Policies
  /?Action=LookupEvents&k=1:
    get:
      summary: Looks up API activity events captured by CloudTrail that create, update,
        or deleten         resources in your account.
      description: Looks up API activity events captured by CloudTrail that create,
        update, or delete         resources in your account.
      operationId: LookupEvents
      parameters:
      - in: query
        name: EndTime
        description: Specifies that only events that occur before or at the specified
          time are returned. If the specified end time is before the specified start
          time, an error is returned.
        type: string
      - in: query
        name: LookupAttributes
        description: Contains a list of lookup attributes. Currently the list can
          contain only one item.
        type: string
      - in: query
        name: MaxResults
        description: The number of events to return. Possible values are 1 through
          50. The default is 10.
        type: string
      - in: query
        name: NextToken
        description: The token to use to get the next page of results after a previous
          API call. This token must be passed in with the same parameters that were
          specified in the the original call. For example, if the original call specified
          an AttributeKey of Username with a value of root, the call with NextToken
          should include those same parameters.
        type: string
      - in: query
        name: StartTime
        description: Specifies that only events that occur after or at the specified
          time are returned. If the specified start time is after the specified end
          time, an error is returned.
        type: string
      responses:
        200:
          description: OK
      tags:
      - Events
  /?Action=PutEventSelectors&k=1:
    get:
      summary: Configures an event selector for your trail.
      description: Configures an event selector for your trail.
      operationId: PutEventSelectors
      parameters:
      - in: query
        name: EventSelectors
        description: Specifies the settings for your event selectors. You can configure
          up to five event selectors for a trail.
        type: string
      - in: query
        name: TrailName
        description: 'Specifies the name of the trail or trail ARN. If you specify
          a trail name, the         string must meet the following requirements:'
        type: string
      responses:
        200:
          description: OK
      tags:
      - Events
  /?Action=RemoveTags&k=1:
    get:
      summary: Removes the specified tags from a trail.
      description: Removes the specified tags from a trail.
      operationId: RemoveTags
      parameters:
      - in: query
        name: ResourceId
        description: 'Specifies the ARN of the trail from which tags should be removed.
          The format of a trail ARN is:'
        type: string
      - in: query
        name: TagsList
        description: Specifies a list of tags to be removed.
        type: string
      responses:
        200:
          description: OK
      tags:
      - Tags
  /?Action=StartLogging&k=1:
    get:
      summary: Starts the recording of AWS API calls and log file delivery for a trail.
      description: Starts the recording of AWS API calls and log file delivery for
        a trail.
      operationId: StartLogging
      parameters:
      - in: query
        name: Name
        description: 'Specifies the name or the CloudTrail ARN of the trail for which
          CloudTrail logs AWS API calls. The format of a trail ARN is:'
        type: string
      responses:
        200:
          description: OK
      tags:
      - Logging
  /?Action=StopLogging&k=1:
    get:
      summary: Suspends the recording of AWS API calls and log file delivery for the
        specified trail.
      description: Suspends the recording of AWS API calls and log file delivery for
        the specified trail.
      operationId: StopLogging
      parameters:
      - in: query
        name: Name
        description: 'Specifies the name or the CloudTrail ARN of the trail for which
          CloudTrail will stop logging AWS API calls. The format of a trail ARN is:'
        type: string
      responses:
        200:
          description: OK
      tags:
      - Logging
  /?Action=UpdateTrail&k=1:
    get:
      summary: Updates the settings that specify delivery of log files.
      description: Updates the settings that specify delivery of log files.
      operationId: UpdateTrail
      parameters:
      - in: query
        name: CloudWatchLogsLogGroupArn
        description: Specifies a log group name using an Amazon Resource Name (ARN),
          a unique identifier that represents the log group to which CloudTrail logs
          will be delivered. Not required unless you specify CloudWatchLogsRoleArn.
        type: string
      - in: query
        name: CloudWatchLogsRoleArn
        description: Specifies the role for the CloudWatch Logs endpoint to assume
          to write to a users log group.
        type: string
      - in: query
        name: EnableLogFileValidation
        description: Specifies whether log file validation is enabled. The default
          is false.
        type: string
      - in: query
        name: IncludeGlobalServiceEvents
        description: Specifies whether the trail is publishing events from global
          services such as IAM to the log files.
        type: string
      - in: query
        name: IsMultiRegionTrail
        description: Specifies whether the trail applies only to the current region
          or to all regions. The default is false. If the trail exists only in the
          current region and this value is set to true, shadow trails (replications
          of the trail) will be created in the other regions. If the trail exists
          in all regions and this value is set to false, the trail will remain in
          the region where it was created, and its shadow trails in other regions
          will be deleted.
        type: string
      - in: query
        name: KmsKeyId
        description: Specifies the KMS key ID to use to encrypt the logs delivered
          by CloudTrail. The value can be a an alias name prefixed by alias/, a fully
          specified ARN to an alias, a fully specified ARN to a key, or a globally
          unique identifier.
        type: string
      - in: query
        name: Name
        description: 'Specifies the name of the trail or trail ARN. If Name is a trail
          name, the         string must meet the following requirements:'
        type: string
      - in: query
        name: S3BucketName
        description: Specifies the name of the Amazon S3 bucket designated for publishing
          log files. See Amazon S3 Bucket Naming Requirements.
        type: string
      - in: query
        name: S3KeyPrefix
        description: Specifies the Amazon S3 key prefix that comes after the name
          of the bucket you have designated         for log file delivery. For more
          information, see Finding Your CloudTrail Log Files. The maximum length is
          200 characters.
        type: string
      - in: query
        name: SnsTopicName
        description: Specifies the name of the Amazon SNS topic defined for notification
          of log file delivery. The maximum length is 256 characters.
        type: string
      responses:
        200:
          description: OK
      tags:
      - Trails
definitions: []